# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'LocationNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocationNote
  pod 'SwiftLint'
  pod 'R.swift'

  target 'LocationNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocationNoteUITests' do
    # Pods for testing
  end

end
